version: '3.8'

services:
  menu-service:
    build:
      context: ./menu-services
    ports:
      - "3001:3001"
    env_file:
      - ./menu-services/.env
    container_name: menu-service

  order-service:
    build:
      context: ./order-services
    ports:
      - "3002:3002"
    env_file:
      - ./order-services/.env
    container_name: order-service

  payment-service:
    build:
      context: ./payment-services
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment_db
      - ORDER_SERVICES_URI=http://order-service:3002
    container_name: payment-service
    depends_on:
      - mongodb
      - order-service

  inventory-service:
    build:
      context: ./inventory-services
    ports:
      - "3004:3004"
    env_file:
      - ./inventory-services/.env
    container_name: inventory-service

  customer-service:
    build:
      context: ./customer-services
    ports:
      - "3005:3005"
    env_file:
      - ./customer-services/.env
    container_name: customer-service

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      MENU_SERVICES_URI: http://menu-service:3001
      ORDER_SERVICES_URI: http://order-service:3002
      PAYMENT_SERVICES_URI: http://payment-service:3003
      INVENTORY_SERVICES_URI: http://inventory-service:3004
      CUSTOMER_SERVICES_URI: http://customer-service:3005
    container_name: api-gateway
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: