name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [api-gateway, menu-services, order-services, payment-services, inventory-services, customer-services]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/cafe-${{ matrix.service }}:latest
          ${{ env.DOCKER_HUB_USERNAME }}/cafe-${{ matrix.service }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/cafe-${{ matrix.service }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/cafe-${{ matrix.service }}:buildcache,mode=max